site_name: Quote Pipeline
repo_url: https://github.com/doug-pires/quotes_dbx
repo_name: doug-pires/quotes_dbx
edit_uri: /tree/main/docs

nav:
  - Home: index.md
  - Configuration Logging: logging.md
  - Common Functions: common_functions.md
  - Use Case Functions: use_case_functions.md
  - References: references.md
  - Curiosities: curiosity.md

theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
    accent: cyan
  logo: &logo assets/quotes_logo.png
  favicon: *logo
  features:
    - navigation.footer
    # - header.autohide

plugins:
  - macros
  - search
  - mkdocstrings
# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/doug-pires
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/douglaspiresm/
  # Jinja to include that {{ commands.run_dbx }}
  commands:
    run_dbx: poetry run dbx

markdown_extensions:
  - attr_list
  - pymdownx.emoji
