# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Quotes Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Poetry version 1.5.1
        run: |
          pip install poetry==1.5.1

      - name: Install dev dependencies
        run: |
          poetry install --with dev

      - name: Check what I have available
        run: |
          echo $(ls)

      - name: Run Pytest and Coverage
        run: |
          poetry run pytest --cov=quotes --cov-fail-under=80 tests/

  deploy:
    runs-on: ubuntu-latest
    env:
      projectcode: quotes
    name: Steps to Deploy the Source Code to Databricks
    steps:
      - name: Deploy to Databricks
        run: echo "Project folder is ${{ vars.projectcode }}"
